inherit_from:
- .rubocop_todo.yml

inherit_gem:
  relaxed-rubocop: .rubocop.yml

AllCops:
  Exclude:
    - db/schema.rb
    - bin/*
    - 'node_modules/**/*'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false


Metrics/BlockLength:
  Enabled: false
