# Sidekiq config
# example: $ bundle exec sidekiq -C config/sidekiq.yml
:verbose: false
:concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] || 10 %>
:timeout: 20

# Sidekiq will run this file through ERB when reading it so you can
# even put in dynamic logic, like a host-specific queue.
# http://www.mikeperham.com/2013/11/13/advanced-sidekiq-host-specific-queues/
:queues:
  - default
  - mailers
  - schedules
  - long_running

max_retries: <%= ENV['SIDEKIQ_MAX_RETRIES'] || 3 %> # (https://github.com/mperham/sidekiq/wiki/Error-Handling)


# you can override concurrency based on environment
# production:
#   :concurrency: 25
# staging:
#   :concurrency: 15
