# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: RubyTestCI

# these are triggers of these worfkow jobs then when it will be run and on which branch it will be run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# defined the All ENV variable which will be used in the this workflow jobs
env:
  POSTGRES_HOST: localhost
  POSTGRES_PORT: 5432
  POSTGRES_PASSWORD: postgres
  POSTGRES_USER: postgres
  RAILS_ENV: test

jobs:
  test: # it's name of jobs

    runs-on: ubuntu-latest # Need to specify os. It's required for each job

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
      # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
      # change this to (see https://github.com/ruby/setup-ruby#versioning):
      # uses: ruby/setup-ruby@v1
        uses: ruby/setup-ruby@21351ecc0a7c196081abca5dc55b08f085efe09a  # here used the existing github acitons of someone to intall ruby
        # with:
          # ruby-version: 2.5.3
          # bundler-cache: true

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install bundler
        run: gem install bundler:2.1.4

      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - uses: ankane/setup-elasticsearch@v1 # # here used the existing github acitons of someone to intall elasticsearch as it's being used
        with:
          elasticsearch-version: 6

      # Be default postgresql, only password is required for this image. these are default value for others
      # POSTGRES_HOST: localhost
      # POSTGRES_PORT: 5432
      # POSTGRES_PASSWORD: postgres
      # POSTGRES_USER: postgres
      - uses: harmon758/postgresql-action@v1 # here used the existing github acitons of someone to intall postgresql,
        with:
          postgresql version: 11  # See https://hub.docker.com/_/postgres for available versions
          postgresql password: postgres

      - name: Setup Database
        run: bundle exec rails db:setup

      - name: Cache node
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn with node
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - uses: actions/setup-node@v2
        with:
          node-version: 11.4.0

      - name: Install packages using yarn
        run: yarn install

      - name: Compile webpacker assets
        run: bundle exec rails webpacker:compile

      - uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: '6.x'
      - run: redis-cli ping

      - name: Run tests
        run: bundle exec rake test
